FROM node:20-bullseye

WORKDIR /app

# Copy package.json and package-lock.json first
COPY package*.json ./

# Install dependencies inside container (fresh)
RUN npm install

# Copy the rest of the app
COPY . .

EXPOSE 3000

CMD ["npm", "start"]
