export const levels = [
  [
    { words: ["Mesa", "Cadeira", "Sofa", "Estante"], category: "Moveis de casa", difficulty: "facil", color: "#f9df6d" },
    { words: ["Arroz", "Massa", "Batata", "Pao"], category: "Acompanhamentos comuns", difficulty: "facil", color: "#a0c35a" },
    { words: ["Azul", "Verde", "Preto", "Branco"], category: "Cores", difficulty: "facil", color: "#b0c4ef" },
    { words: ["Ler", "Ouvir", "Ver", "Falar"], category: "Acoes do dia a dia", difficulty: "facil", color: "#ba81c5" },
  ],
  [
    { words: ["Garfo", "Faca", "Colher", "Prato"], category: "Mesa posta", difficulty: "facil", color: "#f9df6d" },
    { words: ["Manha", "Tarde", "Noite", "Madrugada"], category: "Partes do dia", difficulty: "facil", color: "#a0c35a" },
    { words: ["Norte", "Sul", "Este", "Oeste"], category: "Pontos cardeais", difficulty: "facil", color: "#b0c4ef" },
    { words: ["Metro", "Comboio", "Autocarro", "Eletrico"], category: "Transportes publicos", difficulty: "medio", color: "#ba81c5" },
  ],
  [
    { words: ["Lisboa", "Porto", "Coimbra", "Faro"], category: "Cidades portuguesas", difficulty: "facil", color: "#f9df6d" },
    { words: ["Tejo", "Douro", "Sado", "Mondego"], category: "Rios de Portugal", difficulty: "medio", color: "#a0c35a" },
    { words: ["Rosa", "Cravo", "Tulipa", "Lirio"], category: "Flores", difficulty: "facil", color: "#b0c4ef" },
    { words: ["Fino", "Bica", "Galao", "Garoto"], category: "Pedidos de cafe ou cerveja", difficulty: "medio", color: "#ba81c5" },
  ],
  [
    { words: ["Camisa", "Casaco", "Saia", "Calca"], category: "Pecas de roupa", difficulty: "facil", color: "#f9df6d" },
    { words: ["Manga", "Gola", "Punho", "Costura"], category: "Partes de roupa", difficulty: "medio", color: "#a0c35a" },
    { words: ["Bota", "Sapato", "Sandalia", "Tenis"], category: "Calcado", difficulty: "facil", color: "#b0c4ef" },
    { words: ["Cinto", "Lenco", "Chapeu", "Relogio"], category: "Acessorios", difficulty: "medio", color: "#ba81c5" },
  ],
  [
    { words: ["Soma", "Divisao", "Produto", "Resto"], category: "Matematica basica", difficulty: "medio", color: "#f9df6d" },
    { words: ["Verbo", "Nome", "Adjetivo", "Adverbio"], category: "Classes de palavras", difficulty: "medio", color: "#a0c35a" },
    { words: ["Ponto", "Virgula", "Aspas", "Travessao"], category: "Pontuacao", difficulty: "facil", color: "#b0c4ef" },
    { words: ["Regua", "Compasso", "Esquadro", "Transferidor"], category: "Geometria", difficulty: "medio", color: "#ba81c5" },
  ],
  [
    { words: ["Bifana", "Prego", "Rissol", "Croquete"], category: "Comida de cafe", difficulty: "facil", color: "#f9df6d" },
    { words: ["Bacalhau", "Polvo", "Dourada", "Sardinha"], category: "Peixe na mesa portuguesa", difficulty: "facil", color: "#a0c35a" },
    { words: ["Assar", "Ferver", "Grelhar", "Estufar"], category: "Formas de cozinhar", difficulty: "medio", color: "#b0c4ef" },
    { words: ["Salsa", "Coentros", "Louro", "Alecrim"], category: "Ervas aromaticas", difficulty: "medio", color: "#ba81c5" },
  ],
  [
    { words: ["Euro", "Libra", "Dolar", "Iene"], category: "Moedas atuais", difficulty: "facil", color: "#f9df6d" },
    { words: ["Escudo", "Real", "Pataca", "Cruzado"], category: "Moedas antigas ou historicas", difficulty: "dificil", color: "#a0c35a" },
    { words: ["Massa", "Guito", "Pilim", "Arame"], category: "Giria para dinheiro", difficulty: "medio", color: "#b0c4ef" },
    { words: ["Banco", "Caixa", "Troco", "Juro"], category: "Dinheiro e banca", difficulty: "medio", color: "#ba81c5" },
  ],
  [
    { words: ["Canto", "Livre", "Fora", "Penalty"], category: "Lances de futebol", difficulty: "facil", color: "#f9df6d" },
    { words: ["Rede", "Baliza", "Campo", "Bancada"], category: "Espacos de jogo", difficulty: "facil", color: "#a0c35a" },
    { words: ["Sueca", "Bisca", "Copas", "Burro"], category: "Jogos de cartas em Portugal", difficulty: "medio", color: "#b0c4ef" },
    { words: ["Xadrez", "Damas", "Domino", "Gamao"], category: "Jogos de tabuleiro", difficulty: "medio", color: "#ba81c5" },
  ],
  [
    { words: ["Janela", "Porta", "Varanda", "Chamine"], category: "Aberturas de casa", difficulty: "facil", color: "#f9df6d" },
    { words: ["Tijolo", "Cimento", "Areia", "Gesso"], category: "Construcao", difficulty: "medio", color: "#a0c35a" },
    { words: ["Cano", "Ralo", "Sifao", "Torneira"], category: "Canalizacao", difficulty: "medio", color: "#b0c4ef" },
    { words: ["Folha", "Linha", "Margem", "Capa"], category: "Caderno", difficulty: "facil", color: "#ba81c5" },
  ],
  [
    { words: ["Agudo", "Grave", "Til", "Cedilha"], category: "Sinais da escrita portuguesa", difficulty: "medio", color: "#f9df6d" },
    { words: ["Fado", "Vira", "Chula", "Corridinho"], category: "Musica e danca tradicional", difficulty: "dificil", color: "#a0c35a" },
    { words: ["Palco", "Plateia", "Camarote", "Bastidor"], category: "Espetaculo", difficulty: "medio", color: "#b0c4ef" },
    { words: ["Tomo", "Nota", "Tempo", "Ritmo"], category: "Musica ou leitura", difficulty: "dificil", color: "#ba81c5" },
  ],
  [
    { words: ["Guarda", "Faro", "Lagos", "Braga"], category: "Cidades que tambem sao palavras", difficulty: "medio", color: "#f9df6d" },
    { words: ["Visao", "Audicao", "Tato", "Olfato"], category: "Sentidos", difficulty: "facil", color: "#a0c35a" },
    { words: ["Vence", "Bate", "Mata", "Derrota"], category: "Ganha contra alguem", difficulty: "medio", color: "#b0c4ef" },
    { words: ["Raso", "Santo", "Livre", "Morto"], category: "Espirito ____", difficulty: "dificil", color: "#ba81c5" },
  ],
  [
    { words: ["Imperial", "Fino", "Caneca", "Girafa"], category: "Cerveja em Portugal", difficulty: "medio", color: "#f9df6d" },
    { words: ["Carioca", "Bica", "Abatanado", "Pingado"], category: "Cafe em Portugal", difficulty: "medio", color: "#a0c35a" },
    { words: ["Branco", "Tinto", "Verde", "Rose"], category: "Tipos de vinho", difficulty: "facil", color: "#b0c4ef" },
    { words: ["Reserva", "Colheita", "Garrafa", "Rolha"], category: "Vinho e adega", difficulty: "medio", color: "#ba81c5" },
  ],
  [
    { words: ["Ouro", "Prata", "Cobre", "Bronze"], category: "Metais e medalhas", difficulty: "facil", color: "#f9df6d" },
    { words: ["Jade", "Safira", "Rubi", "Onix"], category: "Pedras", difficulty: "medio", color: "#a0c35a" },
    { words: ["Azoto", "Helio", "Argon", "Xenon"], category: "Gases nobres ou elementos", difficulty: "dificil", color: "#b0c4ef" },
    { words: ["Atlas", "Andes", "Alpes", "Pirenes"], category: "Cadeias montanhosas", difficulty: "medio", color: "#ba81c5" },
  ],
  [
    { words: ["Peao", "Torre", "Bispo", "Cavalo"], category: "Pecas de xadrez", difficulty: "facil", color: "#f9df6d" },
    { words: ["Rei", "Dama", "Valete", "As"], category: "Cartas de figura ou valor", difficulty: "facil", color: "#a0c35a" },
    { words: ["Roque", "Cheque", "Mate", "Gambito"], category: "Termos de xadrez", difficulty: "dificil", color: "#b0c4ef" },
    { words: ["Paus", "Ouros", "Copas", "Espadas"], category: "Naipes", difficulty: "medio", color: "#ba81c5" },
  ],
  [
    { words: ["Pai", "Mae", "Tio", "Prima"], category: "Familia", difficulty: "facil", color: "#f9df6d" },
    { words: ["Sogro", "Genro", "Nora", "Cunhado"], category: "Familia por casamento", difficulty: "medio", color: "#a0c35a" },
    { words: ["Berco", "Fralda", "Chucha", "Biberon"], category: "Bebe", difficulty: "medio", color: "#b0c4ef" },
    { words: ["Avos", "Netos", "Pais", "Filhos"], category: "Geracoes", difficulty: "medio", color: "#ba81c5" },
  ],
  [
    { words: ["Prego", "Alho", "Pente", "Serra"], category: "Coisas com dentes ou cabeca", difficulty: "dificil", color: "#f9df6d" },
    { words: ["Cabeca", "Olho", "Mao", "Pe"], category: "Partes do corpo em expressoes", difficulty: "facil", color: "#a0c35a" },
    { words: ["Vento", "Ladeira", "Cabra", "Lata"], category: "Pe de ____", difficulty: "dificil", color: "#b0c4ef" },
    { words: ["Mesa", "Cadeira", "Banco", "Sofa"], category: "Onde se senta ou apoia", difficulty: "medio", color: "#ba81c5" },
  ],
  [
    { words: ["Domingo", "Segunda", "Terca", "Quinta"], category: "Dias da semana", difficulty: "facil", color: "#f9df6d" },
    { words: ["Domino", "Segurar", "Terceto", "Quintal"], category: "Comecam como dias da semana", difficulty: "dificil", color: "#a0c35a" },
    { words: ["Nova", "Cheia", "Minguante", "Crescente"], category: "Fases da Lua", difficulty: "medio", color: "#b0c4ef" },
    { words: ["Hora", "Minuto", "Segundo", "Instante"], category: "Tempo", difficulty: "facil", color: "#ba81c5" },
  ],
  [
    { words: ["Brasa", "Bras", "Lagareiro", "Gomes"], category: "Bacalhau a ____", difficulty: "dificil", color: "#f9df6d" },
    { words: ["Arroz", "Leite", "Aletria", "Fatia"], category: "Doces tradicionais", difficulty: "medio", color: "#a0c35a" },
    { words: ["Nata", "Ovos", "Mel", "Acucar"], category: "Ingredientes de doce", difficulty: "facil", color: "#b0c4ef" },
    { words: ["Doce", "Salgado", "Amargo", "Acido"], category: "Sabores", difficulty: "facil", color: "#ba81c5" },
  ],
  [
    { words: ["Cisma", "Teima", "Birra", "Capricho"], category: "Insistencia", difficulty: "medio", color: "#f9df6d" },
    { words: ["Calma", "Sereno", "Manso", "Quieto"], category: "Sem agitacao", difficulty: "medio", color: "#a0c35a" },
    { words: ["Afoito", "Audaz", "Bravio", "Valente"], category: "Corajoso", difficulty: "dificil", color: "#b0c4ef" },
    { words: ["Sisudo", "Severo", "Austero", "Grave"], category: "Muito serio", difficulty: "dificil", color: "#ba81c5" },
  ],
  [
    { words: ["Mira", "Alvo", "Ponto", "Centro"], category: "Para onde se aponta", difficulty: "medio", color: "#f9df6d" },
    { words: ["Linha", "Rede", "Poste", "Trave"], category: "Desporto e limites", difficulty: "medio", color: "#a0c35a" },
    { words: ["Cerca", "Muro", "Grade", "Vedacao"], category: "Separar espacos", difficulty: "medio", color: "#b0c4ef" },
    { words: ["Finta", "Passe", "Drible", "Remate"], category: "Gestos de jogo", difficulty: "medio", color: "#ba81c5" },
  ],
  [
    { words: ["Seara", "Eira", "Leira", "Campo"], category: "Campo agricola", difficulty: "dificil", color: "#f9df6d" },
    { words: ["Foice", "Enxada", "Ancinho", "Arado"], category: "Ferramentas agricolas", difficulty: "medio", color: "#a0c35a" },
    { words: ["Centeio", "Milho", "Trigo", "Aveia"], category: "Cereais", difficulty: "medio", color: "#b0c4ef" },
    { words: ["Vindima", "Poda", "Sacha", "Monda"], category: "Trabalhos do campo", difficulty: "dificil", color: "#ba81c5" },
  ],
  [
    { words: ["Tomo", "Volume", "Capitulo", "Indice"], category: "Livro", difficulty: "medio", color: "#f9df6d" },
    { words: ["Editora", "Autor", "Revisor", "Leitor"], category: "Circuito do livro", difficulty: "medio", color: "#a0c35a" },
    { words: ["Prosa", "Verso", "Rima", "Metro"], category: "Literatura", difficulty: "dificil", color: "#b0c4ef" },
    { words: ["Canto", "Lusos", "Ilhas", "Ninfas"], category: "Ecos d'Os Lusiadas", difficulty: "dificil", color: "#ba81c5" },
  ],
  [
    { words: ["Azulejo", "Calcada", "Varina", "Pregao"], category: "Lisboa tradicional", difficulty: "medio", color: "#f9df6d" },
    { words: ["Ribeira", "Douro", "Caves", "Aliados"], category: "Porto", difficulty: "medio", color: "#a0c35a" },
    { words: ["Queima", "Capa", "Lente", "Fado"], category: "Coimbra academica", difficulty: "dificil", color: "#b0c4ef" },
    { words: ["Levadas", "Laurissilva", "Bolo", "Poncha"], category: "Madeira", difficulty: "dificil", color: "#ba81c5" },
  ],
  [
    { words: ["Bordo", "Popa", "Proa", "Leme"], category: "Barco", difficulty: "medio", color: "#f9df6d" },
    { words: ["Cabo", "Baia", "Foz", "Ilheu"], category: "Costa", difficulty: "medio", color: "#a0c35a" },
    { words: ["Nau", "Caravela", "Galeao", "Fragata"], category: "Embarcacoes historicas", difficulty: "dificil", color: "#b0c4ef" },
    { words: ["Rumo", "Carta", "Astro", "Norte"], category: "Navegacao", difficulty: "dificil", color: "#ba81c5" },
  ],
  [
    { words: ["Siso", "Molar", "Canino", "Incisivo"], category: "Dentes", difficulty: "medio", color: "#f9df6d" },
    { words: ["Coroa", "Raiz", "Esmalte", "Polpa"], category: "Partes do dente", difficulty: "dificil", color: "#a0c35a" },
    { words: ["Trono", "Ceptro", "Reino", "Monarca"], category: "Realeza", difficulty: "medio", color: "#b0c4ef" },
    { words: ["Caule", "Folha", "Fruto", "Flor"], category: "Planta", difficulty: "facil", color: "#ba81c5" },
  ],
  [
    { words: ["Acordo", "Pacto", "Tratado", "Convenio"], category: "Combinacao formal", difficulty: "medio", color: "#f9df6d" },
    { words: ["Modo", "Jeito", "Tino", "Maneira"], category: "Forma de lidar", difficulty: "dificil", color: "#a0c35a" },
    { words: ["Reparo", "Conserto", "Emenda", "Arranjo"], category: "Correcao", difficulty: "dificil", color: "#b0c4ef" },
    { words: ["Jura", "Voto", "Promessa", "Palavra"], category: "Compromisso solene", difficulty: "dificil", color: "#ba81c5" },
  ],
  [
    { words: ["Malha", "Rede", "Trama", "Tecido"], category: "Entrecruzamento", difficulty: "medio", color: "#f9df6d" },
    { words: ["Web", "Site", "Link", "Browser"], category: "Internet", difficulty: "facil", color: "#a0c35a" },
    { words: ["Enredo", "Intriga", "Plano", "Conluio"], category: "Historia ou conspiracao", difficulty: "dificil", color: "#b0c4ef" },
    { words: ["Lance", "Jogada", "Ponto", "Partida"], category: "Termos de jogo", difficulty: "dificil", color: "#ba81c5" },
  ],
  [
    { words: ["Basto", "Vasto", "Largo", "Amplo"], category: "Grande ou espacoso", difficulty: "medio", color: "#f9df6d" },
    { words: ["Mondim", "Cabeceiras", "Celorico", "Ribeira"], category: "Terras do norte", difficulty: "muito dificil", color: "#a0c35a" },
    { words: ["Praca", "Terreiro", "Adro", "Rossio"], category: "Espaco publico", difficulty: "dificil", color: "#b0c4ef" },
    { words: ["Imenso", "Enorme", "Colossal", "Gigante"], category: "Muito grande", difficulty: "medio", color: "#ba81c5" },
  ],
  [
    { words: ["Quina", "Canto", "Aresta", "Vertice"], category: "Geometria com pontas", difficulty: "dificil", color: "#f9df6d" },
    { words: ["Escudo", "Cruz", "Hino", "Bandeira"], category: "Simbolos nacionais ou historicos", difficulty: "muito dificil", color: "#a0c35a" },
    { words: ["Quadra", "Soneto", "Ode", "Haiku"], category: "Formas poeticas", difficulty: "dificil", color: "#b0c4ef" },
    { words: ["Ponta", "Gume", "Fio", "Lamina"], category: "Extremidade cortante", difficulty: "dificil", color: "#ba81c5" },
  ],
  [
    { words: ["Quina", "Zimbo", "Zambo", "Eivar"], category: "Palavras raras de cinco letras", difficulty: "muito dificil", color: "#f9df6d" },
    { words: ["Sestro", "Manha", "Jeito", "Cacoete"], category: "Habito ou mania", difficulty: "dificil", color: "#a0c35a" },
    { words: ["Arraia", "Raia", "Linha", "Limite"], category: "Fronteira", difficulty: "dificil", color: "#b0c4ef" },
    { words: ["Bago", "Grao", "Semente", "Pevide"], category: "Coisas pequenas de fruto", difficulty: "medio", color: "#ba81c5" },
  ],
];
